export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERR = 'LOGIN_ERR'
export const LOAD_USER = 'LOAD_USER'
export const REG_SUCCESS = 'REG_SUCCESS'
export const REG_ERR = 'REG_ERR'
export const LOGOUT = 'LOGOUT'
export const TOG_SIDENAV = 'TOG_SIDENAV'